# spell-checker: disable
tasks:
  - init: npm install
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - streetsidesoftware.code-spell-checker
    - tyriar.sort-lines
