name: Pre run
description: "NPM Install and retrieve current release"
runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      working-directory: scraper
      with:
        node-version: 20
        cache: "npm"
        cache-dependency-path: package-lock.json
    - name: NPM Install
      shell: bash
      working-directory: scraper
      run: npm i
    # Since each job may only update a subset of files, we pull the
    # current release so that we update the release, we have all the files.
    - name: Retrieve Current Release
      shell: bash
      working-directory: scraper
      run: npm run get-cache
