name: Save State Federal Formatted Legislation as JSON

on:
  #  schedule:
  #    - cron: "0 0 * * *" # Run daily at midnight UTC

  # Allow manual running from Github Actions tab
  workflow_dispatch:
    inputs:
      skip_cache:
        type: boolean
        description: Skip pulling from cache?

jobs:
  update_state_federal_legislation_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pre Run
        uses: ./.github/workflows/compose/pre-run
      - name: Run Scraper
        env:
          LEGISCAN_API_KEY: ${{ secrets.LEGISCAN_API_KEY }}
          SKIP_LEGISLATION_CACHE: ${{inputs.skip_legislation_cache}}
        run: npm run pull-legiscan
      # - name: Update Nightly Release
      #   uses: andelf/nightly-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: nightly
      #     name: "Nightly release of legislation $$"
      #     prerelease: false
      #     files: |
      #       ./dist_legislation/*.json
