name: Pull Chicago Legislation as JSON

on:
  # schedule:
  #  - cron: "0 2 * * *" # Run daily at 0200 UTC

  # Allow manual running from Github Actions tab
  workflow_dispatch:
    inputs:
      skip_cache:
        type: boolean
        description: Skip pulling from cache?
jobs:
  update_chicago_legislation_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: NPM Install
        run: npm i
      - name: Run Scraper
        env:
          SKIP_LEGISLATION_CACHE: ${{inputs.skip_legislation_cache}}
        run: npm run pull-councilmatic
      - uses: IsaacShelton/update-existing-release@v1.3.4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          release: "Nightly"
          tag: "nightly"
          replace: false
          files: |
            ./dist_legislation/*.json
