name: Update USA Legislation

on:
  schedule:
    - cron: "0 20 * * *" # Run daily at 22:00 UTC (3pm Central)

  # Allow manual running from Github Actions tab
  workflow_dispatch:
    inputs:
      skip_cache:
        type: boolean
        description: Skip Cache - Force update all legislation?

jobs:
  update_usa_legislation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pre Run
        uses: ./.github/workflows/compose/pre-run

      - name: Update USA
        env:
          LEGISCAN_API_KEY: ${{ secrets.LEGISCAN_API_KEY }}
          SKIP_CACHE: ${{inputs.skip_cache}}
          LOCALE: "usa"
        run: cd scraper && npm run scrape

      - name: Publish
        uses: ./.github/workflows/compose/publish
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
